packages:
  - apps/*
  - packages/*

minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - "@esbuild/aix-ppc64"
  - "@esbuild/android-arm"
  - "@esbuild/android-arm64"
  - "@esbuild/android-x64"
  - "@esbuild/darwin-arm64"
  - "@esbuild/darwin-x64"
  - "@esbuild/freebsd-arm64"
  - "@esbuild/freebsd-x64"
  - "@esbuild/linux-arm"
  - "@esbuild/linux-arm64"
  - "@esbuild/linux-ia32"
  - "@esbuild/linux-loong64"
  - "@esbuild/linux-mips64el"
  - "@esbuild/linux-ppc64"
  - "@esbuild/linux-riscv64"
  - "@esbuild/linux-s390x"
  - "@esbuild/linux-x64"
  - "@esbuild/netbsd-arm64"
  - "@esbuild/netbsd-x64"
  - "@esbuild/openbsd-arm64"
  - "@esbuild/openbsd-x64"
  - "@esbuild/openharmony-arm64"
  - "@esbuild/sunos-x64"
  - "@esbuild/win32-arm64"
  - "@esbuild/win32-ia32"
  - "@esbuild/win32-x64"
  - "esbuild"
  - "@rollup/rollup-android-arm-eabi"
  - "@rollup/rollup-android-arm64"
  - "@rollup/rollup-darwin-arm64"
  - "@rollup/rollup-darwin-x64"
  - "@rollup/rollup-freebsd-arm64"
  - "@rollup/rollup-freebsd-x64"
  - "@rollup/rollup-linux-arm-gnueabihf"
  - "@rollup/rollup-linux-arm-musleabihf"
  - "@rollup/rollup-linux-arm64-gnu"
  - "@rollup/rollup-linux-arm64-musl"
  - "@rollup/rollup-linux-loong64-gnu"
  - "@rollup/rollup-linux-loong64-musl"
  - "@rollup/rollup-linux-ppc64-gnu"
  - "@rollup/rollup-linux-ppc64-musl"
  - "@rollup/rollup-linux-riscv64-gnu"
  - "@rollup/rollup-linux-riscv64-musl"
  - "@rollup/rollup-linux-s390x-gnu"
  - "@rollup/rollup-linux-x64-gnu"
  - "@rollup/rollup-linux-x64-musl"
  - "@rollup/rollup-openbsd-x64"
  - "@rollup/rollup-openharmony-arm64"
  - "@rollup/rollup-win32-arm64-msvc"
  - "@rollup/rollup-win32-ia32-msvc"
  - "@rollup/rollup-win32-x64-gnu"
  - "@rollup/rollup-win32-x64-msvc"
  - "@tailwindcss/node"
  - "@tailwindcss/oxide"
  - "@tailwindcss/oxide-android-arm64"
  - "@tailwindcss/oxide-darwin-arm64"
  - "@tailwindcss/oxide-darwin-x64"
  - "@tailwindcss/oxide-freebsd-x64"
  - "@tailwindcss/oxide-linux-arm-gnueabihf"
  - "@tailwindcss/oxide-linux-arm64-gnu"
  - "@tailwindcss/oxide-linux-arm64-musl"
  - "@tailwindcss/oxide-linux-x64-gnu"
  - "@tailwindcss/oxide-linux-x64-musl"
  - "@tailwindcss/oxide-wasm32-wasi"
  - "@tailwindcss/oxide-win32-arm64-msvc"
  - "@tailwindcss/oxide-win32-x64-msvc"
  - "@vitest/expect"
  - "@vitest/mocker"
  - "@vitest/pretty-format"
  - "@vitest/runner"
  - "@vitest/snapshot"
  - "@vitest/spy"
  - "@vitest/utils"
  - "@tailwindcss/vite"
  - "@types/node"
  - "lucide-react"
  - "tailwindcss"
  - "vitest"

blockExoticSubdeps: true
strictDepBuilds: true
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 10080
trustPolicyExclude: []
allowBuilds: {}
