export {
  classificationMetadata,
  comments,
  commitFiles,
  commits,
  concernTags,
  decisionComments,
  decisions,
  diffBlocks,
  one,
  planComments,
  planDecisions,
  planDiffBlocks,
  planItems,
  plans,
  taggings,
  versions,
} from "./schema/reviewTables.js";
export { concernGraphEdges, concernGraphNodes, detectorFindings, detectorRuns } from "./schema/detectorTables.js";
import {
  classificationMetadata,
  comments,
  commitFiles,
  commits,
  concernTags,
  decisionComments,
  decisions,
  diffBlocks,
  planComments,
  planDecisions,
  planDiffBlocks,
  planItems,
  plans,
  taggings,
  versions,
} from "./schema/reviewTables.js";
import { concernGraphEdges, concernGraphNodes, detectorFindings, detectorRuns } from "./schema/detectorTables.js";

export const schemaTables = [
  versions,
  commits,
  commitFiles,
  diffBlocks,
  concernTags,
  taggings,
  classificationMetadata,
  concernGraphNodes,
  concernGraphEdges,
  detectorRuns,
  detectorFindings,
  comments,
  decisions,
  plans,
  planItems,
  planComments,
  planDecisions,
  planDiffBlocks,
  decisionComments,
] as const;
