import type { ConcernMapEntry } from "../schemas/concernDetector/index.js";

export const goalAndCompactionConcernEntries = [
  {
    slug: "goal-continuation",
    label: "Continuation Behavior Around /goal",
    behaviorDefinition:
      "Runtime behavior that turns a persisted active goal into model work without a fresh ordinary user message.",
    seedPaths: [
      { path: "codex-rs/core/src/goals.rs", status: "present" },
      { path: "codex-rs/core/src/codex_thread.rs", status: "present" },
      { path: "codex-rs/core/src/tasks/mod.rs", status: "present" },
      { path: "codex-rs/core/src/tools/registry.rs", status: "present" },
      { path: "codex-rs/app-server/src/request_processors/thread_goal_processor.rs", status: "present" },
      { path: "codex-rs/app-server/src/request_processors/thread_lifecycle.rs", status: "present" },
      { path: "codex-rs/core/templates/goals/continuation.md", status: "present" },
      { path: "codex-rs/core/templates/goals/budget_limit.md", status: "present" },
      { path: "codex-rs/state/src/runtime/goals.rs", status: "present" },
      { path: "codex-rs/state/src/model/thread_goal.rs", status: "present" },
      { path: "codex-rs/app-server/src/thread_state.rs", status: "present" },
      { path: "codex-rs/config/src/config_toml.rs", status: "present" },
      { path: "codex-rs/core/src/event_mapping.rs", status: "present" },
      { path: "codex-rs/core/src/context_manager/history.rs", status: "present" },
    ],
    seedGlobPatterns: [],
    seedSymbols: [
      "GoalRuntimeEvent",
      "GoalRuntimeState",
      "GoalContinuationCandidate",
      "GoalSteeringKind",
      "GoalSteeringMessage",
      "GoalSteeringRole",
      "goal_runtime_apply",
      "maybe_continue_goal_if_idle_runtime",
      "maybe_start_goal_continuation_turn",
      "goal_continuation_candidate_if_active",
      "mark_initial_goal_steering_pending",
      "goal_steering_kind_for",
      "take_initial_goal_steering",
      "mark_thread_goal_turn_started",
      "finish_thread_goal_turn",
      "handle_thread_goal_task_abort",
      "pause_active_thread_goal_for_interrupt",
      "restore_thread_goal_runtime_after_resume",
      "account_thread_goal_progress",
      "account_thread_goal_before_external_mutation",
      "account_thread_goal_wall_clock_usage",
      "continue_active_goal_if_idle",
      "apply_goal_resume_runtime_effects",
      "prepare_external_goal_mutation",
      "apply_external_goal_set",
      "ThreadGoalStatus::Active",
      "ThreadGoalStatus::Paused",
      "ThreadGoalStatus::BudgetLimited",
      "ThreadGoalStatus::Complete",
      "has_queued_response_items_for_next_turn",
      "has_trigger_turn_mailbox_items",
    ],
    seedStringMarkers: [
      "Begin working toward the active thread goal.",
      "Continue working toward the active thread goal.",
      "When the objective is complete, call update_goal with status \"complete\".",
      "budget_limited",
      "<untrusted_objective>",
    ],
    seedTemplateMarkers: [],
    expansionEdgeTypes: ["calls", "called_by", "mutates", "filters", "dispatches", "reconstructs_history"],
    falsePositiveExclusions: [
      "Generic English use of goal is excluded.",
      "TUI-only display is supporting unless it sends set, resume, pause, clear, or continuation actions.",
      "Tool calls are included only when they affect goal accounting, update_goal, or continuation gating.",
      "Compaction/resume is included only when it affects active-goal continuation ordering or injected steering.",
    ],
    fixtureExpectations: [
      {
        name: "active-goal-idle-continuation",
        description: "A fixture changing idle continuation gating must be found from goal-continuation seeds.",
        required: true,
      },
      {
        name: "goal-steering-template",
        description: "A fixture changing continuation template text must retain prompt marker evidence.",
        required: true,
      },
    ],
  },
  {
    slug: "goal-behavior",
    label: "/goal Behavior Generally",
    behaviorDefinition:
      "The complete user/model/API surface for creating, inspecting, updating, pausing, resuming, replacing, clearing, validating, storing, and displaying thread goals.",
    seedPaths: [
      { path: "codex-rs/core/src/tools/handlers/goal_spec.rs", status: "present" },
      { path: "codex-rs/core/src/tools/handlers/goal.rs", status: "present" },
      { path: "codex-rs/core/src/tools/handlers/goal/create_goal.rs", status: "present" },
      { path: "codex-rs/core/src/tools/handlers/goal/get_goal.rs", status: "present" },
      { path: "codex-rs/core/src/tools/handlers/goal/update_goal.rs", status: "present" },
      { path: "codex-rs/core/src/tools/spec_plan.rs", status: "present" },
      { path: "codex-rs/tools/src/tool_config.rs", status: "present" },
      { path: "codex-rs/core/src/goals.rs", status: "present" },
      { path: "codex-rs/state/src/runtime/goals.rs", status: "present" },
      { path: "codex-rs/state/src/model/thread_goal.rs", status: "present" },
      { path: "codex-rs/state/migrations/0029_thread_goals.sql", status: "present" },
      { path: "codex-rs/tui/src/chatwidget/slash_dispatch.rs", status: "present" },
      { path: "codex-rs/tui/src/app/thread_goal_actions.rs", status: "present" },
      { path: "codex-rs/tui/src/app_server_session.rs", status: "present" },
      { path: "codex-rs/app-server-protocol/src/protocol/v2/thread.rs", status: "present" },
      { path: "codex-rs/app-server-protocol/src/protocol/common.rs", status: "present" },
      { path: "codex-rs/app-server/src/message_processor.rs", status: "present" },
    ],
    seedGlobPatterns: [
      "codex-rs/tui/src/**/goal*.rs",
      "codex-rs/tui/src/**/thread_goal*.rs",
      "codex-rs/app-server/src/**/thread_goal*.rs",
    ],
    seedSymbols: [
      "GET_GOAL_TOOL_NAME",
      "CREATE_GOAL_TOOL_NAME",
      "UPDATE_GOAL_TOOL_NAME",
      "create_get_goal_tool",
      "create_create_goal_tool",
      "create_update_goal_tool",
      "GetGoalHandler",
      "CreateGoalHandler",
      "UpdateGoalHandler",
      "CreateGoalArgs",
      "UpdateGoalArgs",
      "GoalToolResponse",
      "CompletionBudgetReport",
      "SetGoalRequest",
      "CreateGoalRequest",
      "set_thread_goal",
      "create_thread_goal",
      "get_thread_goal",
      "validate_goal_budget",
      "validate_goal_objective",
      "ThreadGoal",
      "ThreadGoalStatus",
      "ThreadGoalUpdate",
      "ThreadGoalAccountingOutcome",
      "ThreadGoalSetParams",
      "ThreadGoalGetParams",
      "ThreadGoalClearParams",
      "ThreadGoalUpdatedNotification",
      "ThreadGoalClearedNotification",
      "SlashCommand::Goal",
      "ThreadGoalSetMode",
    ],
    seedStringMarkers: [
      "/goal",
      "/goal pause",
      "/goal resume",
      "/goal clear",
      "create_goal",
      "get_goal",
      "update_goal",
      "thread/goal/set",
      "thread/goal/get",
      "thread/goal/clear",
      "thread/goal/updated",
      "thread/goal/cleared",
      "active",
      "paused",
      "budget_limited",
      "budgetLimited",
      "complete",
    ],
    seedTemplateMarkers: [],
    expansionEdgeTypes: ["calls", "called_by", "registers", "dispatches", "persists", "serializes", "configures"],
    falsePositiveExclusions: [
      "Generated schema-only diffs are supporting unless they reveal a wire shape change without matching source.",
      "Visual formatting of goal status is low signal unless it changes commands, user actions, or available states.",
      "Generic tool registry changes are excluded unless they affect goal tools.",
    ],
    fixtureExpectations: [
      {
        name: "goal-tool-contract",
        description: "A fixture changing create_goal, get_goal, or update_goal schema must map to goal-behavior.",
        required: true,
      },
      {
        name: "goal-rpc-wire-shape",
        description: "A fixture changing thread/goal app-server protocol shapes must be discoverable.",
        required: true,
      },
    ],
  },
  {
    slug: "context-compaction",
    label: "Context Management And Compaction",
    behaviorDefinition:
      "The code that decides what transcript and history items Codex keeps, normalizes, drops, summarizes, replaces, re-injects, persists, and reconstructs as model-visible context across turns.",
    seedPaths: [
      { path: "codex-rs/core/src/context_manager/history.rs", status: "present" },
      { path: "codex-rs/core/src/context_manager/normalize.rs", status: "present" },
      { path: "codex-rs/core/src/context_manager/updates.rs", status: "present" },
      { path: "codex-rs/core/src/context_manager/mod.rs", status: "present" },
      { path: "codex-rs/core/src/compact.rs", status: "present" },
      { path: "codex-rs/core/src/compact_remote.rs", status: "present" },
      { path: "codex-rs/core/src/compact_remote_v2.rs", status: "present" },
      { path: "codex-rs/core/src/tasks/compact.rs", status: "present" },
      { path: "codex-rs/core/src/session/mod.rs", status: "present" },
      { path: "codex-rs/core/src/session/rollout_reconstruction.rs", status: "present" },
      { path: "codex-rs/core/src/session/turn.rs", status: "present" },
      { path: "codex-rs/core/src/session/handlers.rs", status: "present" },
      { path: "codex-rs/core/templates/compact/prompt.md", status: "present" },
      { path: "codex-rs/core/templates/compact/summary_prefix.md", status: "present" },
      { path: "codex-rs/protocol/src/protocol.rs", status: "present" },
      { path: "codex-rs/rollout/src/policy.rs", status: "present" },
      { path: "codex-rs/thread-store/src/types.rs", status: "present" },
    ],
    seedGlobPatterns: [
      "codex-rs/app-server/src/request_processors/*resume*.rs",
      "codex-rs/app-server/src/request_processors/*rollback*.rs",
      "codex-rs/app-server/src/request_processors/*fork*.rs",
    ],
    seedSymbols: [
      "ContextManager",
      "TotalTokenUsageBreakdown",
      "ContextManager.items",
      "history_version",
      "token_info",
      "reference_context_item",
      "InitialContextInjection",
      "RolloutReconstruction",
      "ActiveReplaySegment",
      "TurnReferenceContextItem",
      "InitialHistory",
      "ResumedHistory",
      "RolloutItem",
      "CompactedItem",
      "TurnContextItem",
      "PreviousTurnSettings",
      "ThreadRolledBackEvent",
      "ResponseItem::Compaction",
      "ResponseItem::ContextCompaction",
      "ContextManager::record_items",
      "ContextManager::for_prompt",
      "ContextManager::normalize_history",
      "ContextManager::replace",
      "ContextManager::drop_last_n_user_turns",
      "ContextManager::trim_pre_turn_context_updates",
      "ContextManager::set_reference_context_item",
      "normalize::ensure_call_outputs_present",
      "build_initial_context",
      "build_settings_update_items",
      "record_context_updates_and_set_reference_context_item",
      "replace_compacted_history",
      "record_initial_history",
      "apply_rollout_reconstruction",
      "reconstruct_history_from_rollout",
      "run_compact_task",
      "run_remote_compact_task",
      "process_compacted_history",
      "should_keep_compacted_history_item",
      "insert_initial_context_before_last_real_user_or_summary",
    ],
    seedStringMarkers: [
      "SUMMARIZATION_PROMPT",
      "SUMMARY_PREFIX",
      "replacement_history",
      "ContextCompaction",
      "ThreadRolledBack",
      "TurnContext",
    ],
    seedTemplateMarkers: [],
    expansionEdgeTypes: ["calls", "called_by", "mutates", "filters", "persists", "reconstructs_history", "serializes"],
    falsePositiveExclusions: [
      "Pure UI rendering of resume pickers, transcript cells, or labels is excluded unless it changes persisted history or model-visible context.",
      "Generic thread list/name/archive/status code is excluded unless it loads, mutates, or reconstructs history.",
      "Goal lifecycle is separate unless the diff also changes replay, compaction, or persisted turn context.",
    ],
    fixtureExpectations: [
      {
        name: "compaction-replacement-history",
        description: "A fixture changing replacement history must map to context-compaction.",
        required: true,
      },
      {
        name: "rollout-reconstruction",
        description: "A fixture changing rollout replay or reconstruction must be discoverable.",
        required: true,
      },
    ],
  }
] satisfies readonly ConcernMapEntry[];
