import type { ConcernMapEntry } from "../schemas/concernDetector/index.js";

export const promptAndContextConcernEntries = [
  {
    slug: "harness-prompts",
    label: "Harness Prompts",
    behaviorDefinition:
      "Model-facing instruction sources and the code path that selects, templates, overrides, and sends those instructions to the model as Responses instructions or prompt input.",
    seedPaths: [
      { path: "codex-rs/models-manager/src/model_info.rs", status: "present" },
      { path: "codex-rs/protocol/src/openai_models.rs", status: "present" },
      { path: "codex-rs/core/src/session/mod.rs", status: "present" },
      { path: "codex-rs/core/src/client_common.rs", status: "present" },
      { path: "codex-rs/core/src/client.rs", status: "present" },
      { path: "codex-rs/models-manager/prompt.md", status: "present" },
      { path: "codex-rs/core/templates/agents/orchestrator.md", status: "present" },
      { path: "codex-rs/core/templates/compact/prompt.md", status: "present" },
      { path: "codex-rs/core/templates/realtime/backend_prompt.md", status: "present" },
    ],
    seedGlobPatterns: [
      "codex-rs/core/templates/model_instructions/*.md",
      "codex-rs/collaboration-mode-templates/templates/*.md",
    ],
    seedSymbols: [
      "BASE_INSTRUCTIONS",
      "DEFAULT_PERSONALITY_HEADER",
      "LOCAL_FRIENDLY_TEMPLATE",
      "LOCAL_PRAGMATIC_TEMPLATE",
      "PERSONALITY_PLACEHOLDER",
      "ModelInfo",
      "ModelMessages",
      "ModelInstructionsVariables",
      "ModelInfo::get_model_instructions",
      "with_config_overrides",
      "model_info_from_slug",
      "local_personality_messages_for_slug",
      "BaseInstructions",
      "Prompt",
      "Prompt::get_formatted_input",
      "SessionConfiguration::base_instructions",
      "Codex::get_base_instructions",
      "build_prompt",
      "build_responses_request",
      "include_str!",
    ],
    seedStringMarkers: [
      "base_instructions",
      "model_messages",
      "instructions_template",
      "model_instructions_file",
      "developer_instructions",
      "compact_prompt",
    ],
    seedTemplateMarkers: ["{{ personality }}"],
    expansionEdgeTypes: ["include_str", "calls", "called_by", "configures", "serializes", "matches_marker"],
    falsePositiveExclusions: [
      "Ordinary TUI copy is excluded unless it is injected into model input.",
      "Model metadata is excluded unless it affects instruction selection, prompt templates, or model-visible behavior.",
      "Tool schema descriptions belong to tool affordances unless the change also moves prompt authority.",
    ],
    fixtureExpectations: [
      {
        name: "instructions-request-path",
        description: "A fixture changing rendered Responses instructions must produce a harness-prompts seed hit.",
        required: true,
      },
      {
        name: "template-marker-path",
        description: "A fixture touching model instruction templates must preserve template marker evidence.",
        required: true,
      },
    ],
  },
  {
    slug: "message-roles",
    label: "Message Roles",
    behaviorDefinition:
      "How Codex assigns authority and visibility through message roles such as system, developer, user, and assistant, including role-like phases.",
    seedPaths: [
      { path: "codex-rs/protocol/src/models.rs", status: "present" },
      { path: "codex-rs/core/src/context/fragment.rs", status: "present" },
      { path: "codex-rs/core/src/context_manager/updates.rs", status: "present" },
      { path: "codex-rs/core/src/session/mod.rs", status: "present" },
      { path: "codex-rs/core/src/event_mapping.rs", status: "present" },
      { path: "codex-rs/core/src/context/mod.rs", status: "present" },
      { path: "codex-rs/core/src/context_manager/history.rs", status: "present" },
      { path: "codex-rs/core/src/session/turn.rs", status: "present" },
      { path: "codex-rs/config/src/config_toml.rs", status: "present" },
      { path: "codex-rs/core/src/codex_thread.rs", status: "present" },
    ],
    seedGlobPatterns: [],
    seedSymbols: [
      "ResponseInputItem::Message",
      "ResponseItem::Message",
      "ContentItem::InputText",
      "ContentItem::OutputText",
      "MessagePhase",
      "ContextualUserFragment::ROLE",
      "ContextualUserFragment::into",
      "build_developer_update_item",
      "build_contextual_user_message",
      "build_text_message",
      "GoalSteeringRole",
      "GoalSteeringRole::as_response_role",
      "parse_user_message",
      "parse_turn_item",
      "handle_assistant_item_done_in_plan_mode",
      "maybe_complete_plan_item_from_message",
    ],
    seedStringMarkers: ["system", "developer", "user", "assistant"],
    seedTemplateMarkers: [],
    expansionEdgeTypes: ["calls", "called_by", "maps_role", "filters", "serializes", "configures"],
    falsePositiveExclusions: [
      "Unrelated role wording for auth, CSS, UI, or user identity is excluded.",
      "Generic user strings are excluded unless they appear in role-bearing AST context.",
      "Assistant rendering is included only when it changes parsing, filtering, replay, phase, or authority semantics.",
    ],
    fixtureExpectations: [
      {
        name: "role-literal-match-arm",
        description: "A fixture changing a role literal or role match arm must map to message-roles.",
        required: true,
      },
      {
        name: "contextual-role-fragment",
        description: "A fixture adding a ContextualUserFragment ROLE must be discoverable.",
        required: true,
      },
    ],
  },
  {
    slug: "hidden-context",
    label: "Hidden Context",
    behaviorDefinition:
      "Harness-injected model-visible context that should not behave like ordinary user text in transcript parsing, replay, rollback, compaction, or UI mapping.",
    seedPaths: [
      { path: "codex-rs/core/src/context/fragment.rs", status: "present" },
      { path: "codex-rs/core/src/context/contextual_user_message.rs", status: "present" },
      { path: "codex-rs/core/src/event_mapping.rs", status: "present" },
      { path: "codex-rs/core/src/context_manager/history.rs", status: "present" },
      { path: "codex-rs/core/src/session/mod.rs", status: "present" },
      { path: "codex-rs/core/src/context/user_instructions.rs", status: "present" },
      { path: "codex-rs/core/src/context/skill_instructions.rs", status: "present" },
      { path: "codex-rs/core/src/context/user_shell_command.rs", status: "present" },
      { path: "codex-rs/core/src/context/turn_aborted.rs", status: "present" },
      { path: "codex-rs/core/src/context/subagent_notification.rs", status: "present" },
      { path: "codex-rs/core/src/context/permissions_instructions.rs", status: "present" },
      { path: "codex-rs/core/src/context/model_switch_instructions.rs", status: "present" },
      { path: "codex-rs/core/src/context/collaboration_mode_instructions.rs", status: "present" },
      { path: "codex-rs/core/src/context/personality_spec_instructions.rs", status: "present" },
      { path: "codex-rs/protocol/src/protocol.rs", status: "present" },
      { path: "codex-rs/core/src/agents_md.rs", status: "present" },
      { path: "codex-rs/core/src/context_manager/updates.rs", status: "present" },
    ],
    seedGlobPatterns: [],
    seedSymbols: [
      "ContextualUserFragment",
      "FragmentRegistration",
      "FragmentRegistrationProxy",
      "CONTEXTUAL_USER_FRAGMENTS",
      "CONTEXTUAL_DEVELOPER_PREFIXES",
      "is_standard_contextual_user_text",
      "is_contextual_user_fragment",
      "parse_visible_hook_prompt_message",
      "is_contextual_user_message_content",
      "is_contextual_dev_message_content",
      "has_non_contextual_dev_message_content",
      "is_contextual_dev_fragment",
      "trim_pre_turn_context_updates",
      "is_user_turn_boundary",
    ],
    seedStringMarkers: [
      "# AGENTS.md instructions for ",
      "</INSTRUCTIONS>",
      "<skill>",
      "<user_shell_command>",
      "<turn_aborted>",
      "<subagent_notification>",
      "<permissions instructions>",
      "<model_switch>",
      "<collaboration_mode>",
      "<realtime_conversation>",
      "<personality_spec>",
      "<apps_instructions>",
      "<skills_instructions>",
      "<plugins_instructions>",
    ],
    seedTemplateMarkers: [],
    expansionEdgeTypes: ["calls", "called_by", "filters", "matches_marker", "serializes", "reconstructs_history"],
    falsePositiveExclusions: [
      "Arbitrary XML-like tags are excluded.",
      "AGENTS discovery alone is excluded unless wrapping, injection, scope, ordering, or source inclusion changes.",
      "Hidden UI state is excluded unless it becomes model-visible input, TurnContext, or persisted/replayed context.",
    ],
    fixtureExpectations: [
      {
        name: "contextual-fragment-registration",
        description: "A fixture adding a contextual fragment must create hidden-context seed evidence.",
        required: true,
      },
      {
        name: "hidden-context-parser",
        description: "A fixture changing contextual message parsing must remain separated from ordinary user text.",
        required: true,
      },
    ],
  }
] satisfies readonly ConcernMapEntry[];
