import type { ConcernMapEntry } from "../schemas/concernDetector/index.js";

export const toolAndPermissionConcernEntries = [
  {
    slug: "tool-affordances",
    label: "Tool Affordances",
    behaviorDefinition:
      "The code that determines what tools the model can see, how those tools are named, described, schema-shaped, searched, deferred, routed, hooked, and serialized back to the model.",
    seedPaths: [
      { path: "codex-rs/tools/src/tool_config.rs", status: "present" },
      { path: "codex-rs/tools/src/tool_spec.rs", status: "present" },
      { path: "codex-rs/tools/src/responses_api.rs", status: "present" },
      { path: "codex-rs/tools/src/tool_definition.rs", status: "present" },
      { path: "codex-rs/tools/src/tool_discovery.rs", status: "present" },
      { path: "codex-rs/tools/src/mcp_tool.rs", status: "present" },
      { path: "codex-rs/tools/src/dynamic_tool.rs", status: "present" },
      { path: "codex-rs/core/src/tools/spec.rs", status: "present" },
      { path: "codex-rs/core/src/tools/spec_plan.rs", status: "present" },
      { path: "codex-rs/core/src/tools/registry.rs", status: "present" },
      { path: "codex-rs/core/src/tools/context.rs", status: "present" },
      { path: "codex-rs/core/src/tools/orchestrator.rs", status: "present" },
      { path: "codex-rs/core/src/mcp_tool_exposure.rs", status: "present" },
      { path: "codex-rs/core/src/mcp_tool_call.rs", status: "present" },
      { path: "codex-rs/codex-mcp/src/connection_manager.rs", status: "present" },
      { path: "codex-rs/codex-mcp/src/tools.rs", status: "present" },
      { path: "codex-rs/protocol/src/dynamic_tools.rs", status: "present" },
    ],
    seedGlobPatterns: [
      "codex-rs/core/src/tools/handlers/**/*.rs",
      "codex-rs/app-server/src/**/*dynamic_tool*.rs",
      "codex-rs/app-server/src/**/*mcp*.rs",
      "codex-rs/**/**/*hook*.rs",
    ],
    seedSymbols: [
      "ToolsConfig",
      "ToolsConfigParams",
      "ToolEnvironmentMode",
      "ToolSpec",
      "ConfiguredToolSpec",
      "ResponsesApiTool",
      "ResponsesApiNamespace",
      "LoadableToolSpec",
      "FreeformTool",
      "create_tools_json_for_responses_api",
      "tool_definition_to_responses_api_tool",
      "mcp_tool_to_responses_api_tool",
      "dynamic_tool_to_responses_api_tool",
      "coalesce_loadable_tool_specs",
      "build_tool_registry_builder",
      "ToolRegistryBuilder",
      "register_handler",
      "push_spec",
      "ToolRegistry::dispatch_any",
      "ToolHandler",
      "ToolKind",
      "supports_parallel_tool_calls",
      "is_mutating",
      "pre_tool_use_payload",
      "post_tool_use_payload",
      "ToolInvocation",
      "ToolPayload",
      "ToolOutput",
      "ToolSearchHandler",
      "TOOL_SEARCH_TOOL_NAME",
      "McpHandler",
      "handle_mcp_tool_call",
      "normalize_tools_for_model",
      "DynamicToolSpec",
      "DynamicToolHandler",
    ],
    seedStringMarkers: [
      "exec_command",
      "write_stdin",
      "shell",
      "tool_search",
      "request_permissions",
      "web_search",
      "image_generation",
      "apply_patch",
      "defer_loading",
      "parameters",
      "output_schema",
      "strict",
      "additionalProperties",
    ],
    seedTemplateMarkers: [],
    expansionEdgeTypes: ["calls", "called_by", "registers", "dispatches", "surfaces_tool", "serializes", "filters"],
    falsePositiveExclusions: [
      "Generic business logic inside a tool is excluded unless it changes schema, output serialization, approval behavior, mutability, hooks, or model-visible errors.",
      "Telemetry-only changes are excluded unless they change dispatch, filtering, MCP metadata, or model-facing result shape.",
      "Generated schema-only changes are supporting unless wire names or shapes changed.",
    ],
    fixtureExpectations: [
      {
        name: "tool-schema-description",
        description: "A fixture changing model-visible tool names, descriptions, or parameter shapes must map here.",
        required: true,
      },
      {
        name: "mcp-dynamic-tool",
        description: "A fixture changing MCP or dynamic tool conversion must be discoverable.",
        required: true,
      },
    ],
  },
  {
    slug: "permission-defaults",
    label: "Permission Defaults",
    behaviorDefinition:
      "The code that determines Codex's starting approval policy, sandbox/permission profile, network/filesystem posture, escalation path, and model-visible permission instructions before a tool call happens.",
    seedPaths: [
      { path: "codex-rs/protocol/src/protocol.rs", status: "present" },
      { path: "codex-rs/protocol/src/models.rs", status: "present" },
      { path: "codex-rs/protocol/src/permissions.rs", status: "present" },
      { path: "codex-rs/protocol/src/request_permissions.rs", status: "present" },
      { path: "codex-rs/protocol/src/config_types.rs", status: "present" },
      { path: "codex-rs/config/src/config_toml.rs", status: "present" },
      { path: "codex-rs/config/src/permissions_toml.rs", status: "present" },
      { path: "codex-rs/core/src/config/permissions.rs", status: "present" },
      { path: "codex-rs/core/src/config/mod.rs", status: "present" },
      { path: "codex-rs/core/src/context/permissions_instructions.rs", status: "present" },
      { path: "codex-rs/core/src/tools/sandboxing.rs", status: "present" },
      { path: "codex-rs/core/src/tools/orchestrator.rs", status: "present" },
      { path: "codex-rs/sandboxing/src/manager.rs", status: "present" },
      { path: "codex-rs/sandboxing/src/policy_transforms.rs", status: "present" },
    ],
    seedGlobPatterns: [
      "codex-rs/core/src/context/prompts/permissions/**/*.md",
      "codex-rs/**/**/*permission*.rs",
      "codex-rs/**/**/*sandbox*.rs",
    ],
    seedSymbols: [
      "AskForApproval",
      "GranularApprovalConfig",
      "allows_sandbox_approval",
      "allows_request_permissions",
      "allows_mcp_elicitations",
      "SandboxMode",
      "SandboxPolicy",
      "PermissionProfile",
      "ActivePermissionProfile",
      "ActivePermissionProfileModification",
      "SandboxEnforcement",
      "SandboxPermissions",
      "FileSystemSandboxPolicy",
      "NetworkSandboxPolicy",
      "NetworkAccess",
      "BUILT_IN_READ_ONLY_PROFILE",
      "BUILT_IN_WORKSPACE_PROFILE",
      "BUILT_IN_DANGER_NO_SANDBOX_PROFILE",
      "default_builtin_permission_profile_name",
      "builtin_permission_profile",
      "derive_permission_profile",
      "ConfigToml",
      "PermissionsToml",
      "PermissionProfileToml",
      "compile_permission_profile_selection",
      "compile_permission_profile",
      "PermissionsInstructions",
      "PermissionsInstructions::from_permission_profile",
      "sandbox_prompt_from_profile",
      "approval_text",
      "sandbox_text",
      "default_exec_approval_requirement",
      "ExecApprovalRequirement",
      "ToolOrchestrator::run",
      "ToolOrchestrator::request_approval",
      "SandboxOverride",
      "RequestPermissionsArgs",
      "AdditionalPermissionProfile",
      "normalize_additional_permissions",
      "merge_permission_profiles",
      "intersect_permission_profiles",
      "SandboxManager::select_initial",
      "SandboxManager::transform",
    ],
    seedStringMarkers: [
      "approval_policy",
      "sandbox_mode",
      "default_permissions",
      "include_permissions_instructions",
      "on-request",
      "on-failure",
      "never",
      "read-only",
      "workspace-write",
      "danger-full-access",
    ],
    seedTemplateMarkers: [],
    expansionEdgeTypes: ["calls", "called_by", "configures", "gates_permission", "serializes", "filters", "mutates"],
    falsePositiveExclusions: [
      "Generic command execution internals are excluded unless they alter approval, sandbox selection, permissions, or model-visible permission instructions.",
      "Pure display/status changes are excluded unless they alter defaults, user choices, or persisted permission state.",
      "Network proxy internals are excluded unless they change how permission profiles enable or restrict network access.",
    ],
    fixtureExpectations: [
      {
        name: "permission-profile-default",
        description: "A fixture changing default permission profile derivation must map to permission-defaults.",
        required: true,
      },
      {
        name: "permission-instruction-template",
        description: "A fixture changing permission prompt templates must remain model-visible evidence.",
        required: true,
      },
    ],
  }
] satisfies readonly ConcernMapEntry[];
