import { z } from "zod";
import {
  AddCommentParamsSchema,
  ClassifyCommitParamsSchema,
  ClassifyFileParamsSchema,
  ClassificationViewSchema,
  CloseVersionParamsSchema,
  CommentDetailSchema,
  CommentSummarySchema,
  CommitDetailSchema,
  CommitFileDetailSchema,
  CommitFileQueueItemSchema,
  CommitQueueItemSchema,
  CompletePlanParamsSchema,
  ConcernGraphEdgeSchema,
  ConcernGraphNodeSchema,
  ConcernMapEntrySchema,
  ConcernSeedPathSchema,
  ConcernTagViewSchema,
  CreatePlanItemParamsSchema,
  CreatePlanParamsSchema,
  CreateTaggingParamsSchema,
  DecisionDetailSchema,
  DecisionSummarySchema,
  DeleteTaggingParamsSchema,
  DetectorFindingSchema,
  DetectorFindingSummarySchema,
  DetectorRunSchema,
  DiffBlockViewSchema,
  FileReviewViewSchema,
  FinalizeDecisionParamsSchema,
  NextActionHintSchema,
  OverrideCommitStatusParamsSchema,
  OverrideFileStatusParamsSchema,
  PaginatedResponseSchema,
  PlanDetailSchema,
  PlanItemDetailSchema,
  PlanSummarySchema,
  PopulateNextVersionParamsSchema,
  PopulateNextVersionResponseSchema,
  ProposeDecisionParamsSchema,
  RemainingWorkSchema,
  ReopenCommentParamsSchema,
  ResolveCommentParamsSchema,
  TaggingViewSchema,
  UpdateDecisionParamsSchema,
  UpdatePlanItemParamsSchema,
  UpdatePlanParamsSchema,
  VersionDetailSchema,
  VersionProgressSchema,
  VersionSummarySchema,
} from "./schemas/index.js";

export const boundarySchemas = {
  PopulateNextVersionParams: PopulateNextVersionParamsSchema,
  PopulateNextVersionResponse: PopulateNextVersionResponseSchema,
  ClassifyCommitParams: ClassifyCommitParamsSchema,
  ClassifyFileParams: ClassifyFileParamsSchema,
  OverrideCommitStatusParams: OverrideCommitStatusParamsSchema,
  OverrideFileStatusParams: OverrideFileStatusParamsSchema,
  CreateTaggingParams: CreateTaggingParamsSchema,
  DeleteTaggingParams: DeleteTaggingParamsSchema,
  AddCommentParams: AddCommentParamsSchema,
  ResolveCommentParams: ResolveCommentParamsSchema,
  ReopenCommentParams: ReopenCommentParamsSchema,
  ProposeDecisionParams: ProposeDecisionParamsSchema,
  UpdateDecisionParams: UpdateDecisionParamsSchema,
  FinalizeDecisionParams: FinalizeDecisionParamsSchema,
  CreatePlanParams: CreatePlanParamsSchema,
  UpdatePlanParams: UpdatePlanParamsSchema,
  CreatePlanItemParams: CreatePlanItemParamsSchema,
  UpdatePlanItemParams: UpdatePlanItemParamsSchema,
  CompletePlanParams: CompletePlanParamsSchema,
  CloseVersionParams: CloseVersionParamsSchema,
  ConcernSeedPath: ConcernSeedPathSchema,
  ConcernMapEntry: ConcernMapEntrySchema,
  ConcernGraphNode: ConcernGraphNodeSchema,
  ConcernGraphEdge: ConcernGraphEdgeSchema,
  DetectorRun: DetectorRunSchema,
  DetectorFinding: DetectorFindingSchema,
  DetectorFindingSummary: DetectorFindingSummarySchema,
  VersionSummary: VersionSummarySchema,
  VersionDetail: VersionDetailSchema,
  VersionProgress: VersionProgressSchema,
  CommitQueueItem: CommitQueueItemSchema,
  CommitDetail: CommitDetailSchema,
  CommitFileQueueItem: CommitFileQueueItemSchema,
  CommitFileDetail: CommitFileDetailSchema,
  DiffBlockView: DiffBlockViewSchema,
  FileReviewView: FileReviewViewSchema,
  ConcernTagView: ConcernTagViewSchema,
  TaggingView: TaggingViewSchema,
  ClassificationView: ClassificationViewSchema,
  CommentSummary: CommentSummarySchema,
  CommentDetail: CommentDetailSchema,
  DecisionSummary: DecisionSummarySchema,
  DecisionDetail: DecisionDetailSchema,
  PlanSummary: PlanSummarySchema,
  PlanDetail: PlanDetailSchema,
  PlanItemDetail: PlanItemDetailSchema,
  RemainingWork: RemainingWorkSchema,
  PaginatedResponse: PaginatedResponseSchema,
  NextActionHint: NextActionHintSchema,
} as const;

export type BoundarySchemaName = keyof typeof boundarySchemas;
export type BoundaryJsonSchema = unknown;
export type BoundaryJsonSchemas = Record<BoundarySchemaName, BoundaryJsonSchema>;

export function toBoundaryJsonSchema(name: BoundarySchemaName): BoundaryJsonSchema {
  return z.toJSONSchema(boundarySchemas[name], { reused: "ref" });
}

export function exportBoundaryJsonSchemas(): BoundaryJsonSchemas {
  return Object.fromEntries(
    Object.keys(boundarySchemas).map((name) => [
      name,
      toBoundaryJsonSchema(name as BoundarySchemaName),
    ]),
  ) as BoundaryJsonSchemas;
}
