export type ConcernTagSeed = {
  slug: string;
  label: string;
  parentSlug: string | null;
  description: string;
  examples: string[];
  pitfalls: string[];
  sortOrder: number;
};

const topLevelSeeds: ConcernTagSeed[] = [
  {
    slug: "goal-steering-contract",
    label: "Goal Steering Contract",
    parentSlug: null,
    description: "Changes that affect how user goals are created, interpreted, updated, or audited.",
    examples: ["Goal initialization prompts", "Completion checks"],
    pitfalls: ["Treating ordinary status text as goal authority"],
    sortOrder: 100,
  },
  {
    slug: "message-role-authority",
    label: "Message Role Authority",
    parentSlug: null,
    description: "Changes that affect which role owns instructions, frames, policies, or runtime steering.",
    examples: ["System frame movement", "Configurable role text"],
    pitfalls: ["Letting lower-authority content override runtime-owned frames"],
    sortOrder: 200,
  },
  {
    slug: "prompt-source-authority",
    label: "Prompt Source Authority",
    parentSlug: null,
    description: "Changes that affect which prompt sources are trusted or how their evidence is presented.",
    examples: ["Artifact proof requirements", "Prompt source ordering"],
    pitfalls: ["Confusing proximity with authority"],
    sortOrder: 300,
  },
  {
    slug: "hidden-context-transcript",
    label: "Hidden Context Transcript",
    parentSlug: null,
    description: "Changes that affect hidden context, transcript markers, or leakage into visible turns.",
    examples: ["Goal context markers", "Compacted hidden history"],
    pitfalls: ["Accidentally exposing internal transcript structure"],
    sortOrder: 400,
  },
  {
    slug: "continuation-lifecycle",
    label: "Continuation Lifecycle",
    parentSlug: null,
    description: "Changes that affect interruption, resumption, suppression, or continuation behavior.",
    examples: ["Thread resume handling", "Interruption pause rules"],
    pitfalls: ["Dropping prior user intent after a lifecycle transition"],
    sortOrder: 500,
  },
  {
    slug: "goal-state-accounting",
    label: "Goal State Accounting",
    parentSlug: null,
    description: "Changes that affect progress, blocked states, usage limits, or accounting of work toward a goal.",
    examples: ["Blocked-state markers", "Usage-limited progress summaries"],
    pitfalls: ["Marking completion without auditing remaining work"],
    sortOrder: 600,
  },
  {
    slug: "tool-execution-surface",
    label: "Tool Execution Surface",
    parentSlug: null,
    description: "Changes that affect tool discovery, invocation affordances, or MCP contract behavior.",
    examples: ["Tool list construction", "MCP call contract changes"],
    pitfalls: ["Tagging generic tool plumbing as primary prompt behavior"],
    sortOrder: 700,
  },
  {
    slug: "permissions-workspace-environment",
    label: "Permissions Workspace Environment",
    parentSlug: null,
    description: "Changes that affect permission defaults, workspace roots, sandboxing, or runtime environment refresh.",
    examples: ["Workspace root detection", "Permission prompt defaults"],
    pitfalls: ["Hiding authority changes inside environment setup"],
    sortOrder: 800,
  },
  {
    slug: "storage-boundary-movement",
    label: "Storage Boundary Movement",
    parentSlug: null,
    description: "Changes that move prompt, goal, or app-server state across storage or extension boundaries.",
    examples: ["Goal store migration", "App-server API state movement"],
    pitfalls: ["Treating persistence movement as prompt behavior without model-input impact"],
    sortOrder: 900,
  },
  {
    slug: "repo-context-durability",
    label: "Repo Context Durability",
    parentSlug: null,
    description: "Changes that affect durable repository context, AGENTS instructions, or compaction history.",
    examples: ["AGENTS.md lookup", "Compaction-history reconstruction"],
    pitfalls: ["Assuming context survives across resumes without explicit carriage"],
    sortOrder: 1000,
  },
];

const childDefinitions: Array<
  readonly [
    slug: string,
    label: string,
    parentSlug: string,
    description: string,
    examples: string[],
    pitfalls: string[],
  ]
> = [
  [
    "goal.initial-steering",
    "Initial Steering",
    "goal-steering-contract",
    "Initial user-goal framing and first-turn steering.",
    ["Goal creation prompts"],
    ["Over-weighting inferred goals"],
  ],
  [
    "goal.continuation",
    "Continuation",
    "goal-steering-contract",
    "How active goals continue across turns and tool work.",
    ["Resume toward current objective"],
    ["Restarting from stale assumptions"],
  ],
  [
    "goal.objective-update",
    "Objective Update",
    "goal-steering-contract",
    "Rules for changing the objective while work is in flight.",
    ["User redirects the goal"],
    ["Silently replacing the objective"],
  ],
  [
    "goal.completion-audit",
    "Completion Audit",
    "goal-steering-contract",
    "Checks that prove the goal is genuinely complete.",
    ["Final remaining-work review"],
    ["Equating command success with task completion"],
  ],
  [
    "role.runtime-owned-frame",
    "Runtime-Owned Frame",
    "message-role-authority",
    "Runtime-owned role frames and their instruction authority.",
    ["Harness-authored system frame"],
    ["Letting config text masquerade as runtime policy"],
  ],
  [
    "role.configurable-steering",
    "Configurable Steering",
    "message-role-authority",
    "User or repo configurable steering text and its role boundaries.",
    ["Custom instructions"],
    ["Giving configurable text hidden-policy authority"],
  ],
  [
    "role.policy-boundary-drift",
    "Policy Boundary Drift",
    "message-role-authority",
    "Movement of behavior across policy or role boundaries.",
    ["Authority copied into another role"],
    ["Missing regression risk from wording moves"],
  ],
  [
    "prompt.artifact-proving-risk",
    "Artifact Proving Risk",
    "prompt-source-authority",
    "How artifacts prove or fail to prove prompt behavior.",
    ["Transcript evidence requirements"],
    ["Accepting artifacts without source validation"],
  ],
  [
    "prompt.proximity-authority",
    "Proximity Authority",
    "prompt-source-authority",
    "Risk that nearby text is treated as more authoritative than it is.",
    ["Adjacent tool output"],
    ["Conflating recency with authority"],
  ],
  [
    "prompt.get-goal-regrounding",
    "Get Goal Regrounding",
    "prompt-source-authority",
    "Use of goal retrieval to reground behavior after drift.",
    ["Goal fetch before finalization"],
    ["Skipping regrounding after interruption"],
  ],
  [
    "prompt.fidelity",
    "Prompt Fidelity",
    "prompt-source-authority",
    "Faithfulness of rendered prompt text to the intended instruction contract.",
    ["Template rendering changes"],
    ["Small wording changes with large behavioral impact"],
  ],
  [
    "hidden.goal-context-marker",
    "Goal Context Marker",
    "hidden-context-transcript",
    "Hidden markers that identify current goal context.",
    ["Internal goal markers"],
    ["Leaking marker text to visible output"],
  ],
  [
    "hidden.visible-leak",
    "Visible Leak",
    "hidden-context-transcript",
    "Hidden or internal context appearing in visible transcript content.",
    ["Internal summary shown to user"],
    ["Treating leaks as cosmetic"],
  ],
  [
    "lifecycle.interrupt-pause",
    "Interrupt Pause",
    "continuation-lifecycle",
    "Behavior when work is interrupted or intentionally paused.",
    ["Pause after user interruption"],
    ["Continuing destructive work after interruption"],
  ],
  [
    "lifecycle.thread-resume",
    "Thread Resume",
    "continuation-lifecycle",
    "Behavior when a thread resumes from persisted or compacted context.",
    ["Resume after compaction"],
    ["Answering an older request after resume"],
  ],
  [
    "lifecycle.suppression",
    "Suppression",
    "continuation-lifecycle",
    "Suppression of work, prompts, or continuation signals.",
    ["Suppress stale tool follow-up"],
    ["Suppressing required user-visible status"],
  ],
  [
    "state.blocked",
    "Blocked State",
    "goal-state-accounting",
    "Representation of blocked work and missing inputs.",
    ["Waiting for user decision"],
    ["Reporting blocked work as complete"],
  ],
  [
    "state.usage-limited",
    "Usage Limited",
    "goal-state-accounting",
    "Behavior when usage budgets or limits constrain progress.",
    ["Token budget accounting"],
    ["Stopping without recording remaining work"],
  ],
  [
    "accounting.progress-lifecycle",
    "Progress Lifecycle",
    "goal-state-accounting",
    "Progress accounting from start through completion or closure.",
    ["Goal status updates"],
    ["Progress state outliving the actual objective"],
  ],
  [
    "tools.discovery-amplifier",
    "Discovery Amplifier",
    "tool-execution-surface",
    "Tool discovery changes that amplify or narrow available actions.",
    ["Available tool rendering"],
    ["Making discovery changes primary when only affordances changed"],
  ],
  [
    "tools.mcp-contract",
    "MCP Contract",
    "tool-execution-surface",
    "MCP tool and resource contract behavior.",
    ["Tool schema change"],
    ["Ignoring client compatibility"],
  ],
  [
    "permissions.workspace-root",
    "Workspace Root",
    "permissions-workspace-environment",
    "Workspace-root selection and its effect on permission scope.",
    ["Root path refresh"],
    ["Expanding access without surfacing it"],
  ],
  [
    "permissions.runtime-refresh",
    "Runtime Refresh",
    "permissions-workspace-environment",
    "Runtime environment refresh and permission-state changes.",
    ["Reloaded sandbox settings"],
    ["Using stale permission state"],
  ],
  [
    "boundary.core-to-extension",
    "Core To Extension",
    "storage-boundary-movement",
    "State or authority moving between core and extension surfaces.",
    ["Extension-owned prompt state"],
    ["Losing source-of-truth clarity"],
  ],
  [
    "boundary.goal-store",
    "Goal Store",
    "storage-boundary-movement",
    "Durable goal storage and retrieval boundaries.",
    ["Goal persistence change"],
    ["Persisting hidden authority without audit"],
  ],
  [
    "boundary.app-server-api",
    "App Server API",
    "storage-boundary-movement",
    "App-server API boundaries that carry prompt or workflow state.",
    ["Thread state endpoint"],
    ["Letting transport shape domain authority"],
  ],
  [
    "context.agents-md",
    "AGENTS.md",
    "repo-context-durability",
    "Repository instruction discovery and durability.",
    ["Instruction file precedence"],
    ["Forgetting nested instruction scope"],
  ],
  [
    "context.compaction-history",
    "Compaction History",
    "repo-context-durability",
    "Context preserved or reconstructed through compaction.",
    ["Compacted summaries"],
    ["Treating summaries as full-fidelity transcripts"],
  ],
];

const childSeeds: ConcernTagSeed[] = childDefinitions.map(
  ([slug, label, parentSlug, description, examples, pitfalls], index) => ({
    slug,
    label,
    parentSlug,
    description,
    examples,
    pitfalls,
    sortOrder: 1100 + index * 10,
  }),
);

export const concernTagSeeds = [...topLevelSeeds, ...childSeeds] as const satisfies readonly ConcernTagSeed[];

export const requiredTopLevelConcernTagSlugs = topLevelSeeds.map((seed) => seed.slug);
export const requiredNestedConcernTagSlugs = childDefinitions.map(([slug]) => slug);
export const concernTagSeedsBySlug = new Map(concernTagSeeds.map((seed) => [seed.slug, seed]));

export const concernTaggingGuidance = {
  primaryTagRule: "Exactly one primary tag per commit/file/block.",
  secondaryTagRule: "Secondary tags are amplifiers.",
  toolTagRule: "Tool tags are usually secondary unless the tool contract itself changed.",
  storageAccountingRule:
    "Storage/accounting tags are not prompt behavior unless model-input construction or authority moved there.",
} as const;
